// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Midicare_eLab.DAL.Data;

#nullable disable

namespace eLab.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326213947_edit result model")]
    partial class editresultmodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsersRoles", (string)null);
                });

            modelBuilder.Entity("Midicare_eLab.DAL.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Midicare_eLab.DAL.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CodeResetPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("eLab.DAL.Models.AIChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContextSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ResultId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientProfileId");

                    b.HasIndex("ResultId");

                    b.ToTable("AIChats");
                });

            modelBuilder.Entity("eLab.DAL.Models.AIChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AIChatId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AIChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("AIChatMessages");
                });

            modelBuilder.Entity("eLab.DAL.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("StaffProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PatientProfileId");

                    b.HasIndex("StaffProfileId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("eLab.DAL.Models.BookingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int");

                    b.Property<int>("TestCatalogId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("OfferId");

                    b.HasIndex("TestCatalogId");

                    b.ToTable("BookingItems");
                });

            modelBuilder.Entity("eLab.DAL.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResultId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("eLab.DAL.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TestCatalogId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TestCatalogId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("eLab.DAL.Models.PatientProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfBrith")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PatientProfiles");
                });

            modelBuilder.Entity("eLab.DAL.Models.PatientRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<bool>("VisibleToPatient")
                        .HasColumnType("bit");

                    b.Property<bool>("VisibleToStaff")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("BranchId");

                    b.HasIndex("PatientProfileId");

                    b.HasIndex("ResultId");

                    b.ToTable("PatientRecords");
                });

            modelBuilder.Entity("eLab.DAL.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("TestCatalogId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TestCatalogId");

                    b.HasIndex("UserId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("eLab.DAL.Models.ReferenceRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeMax")
                        .HasColumnType("int");

                    b.Property<int>("AgeMin")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValueMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValueMin")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ReportTemplateId");

                    b.ToTable("ReferenceRanges");
                });

            modelBuilder.Entity("eLab.DAL.Models.ReportTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldsSchema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestCatalogId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TestCatalogId");

                    b.ToTable("ReportTemplates");
                });

            modelBuilder.Entity("eLab.DAL.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BookingItemId")
                        .HasColumnType("int");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ReportTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("BookingItemId")
                        .IsUnique()
                        .HasFilter("[BookingItemId] IS NOT NULL");

                    b.HasIndex("PatientProfileId");

                    b.HasIndex("ReportTemplateId");

                    b.HasIndex("UploadedById");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Results", (string)null);
                });

            modelBuilder.Entity("eLab.DAL.Models.StaffChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StaffProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("PatientProfileId");

                    b.HasIndex("StaffProfileId");

                    b.ToTable("StaffChats");
                });

            modelBuilder.Entity("eLab.DAL.Models.StaffChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChatId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("StaffChatMessages");
                });

            modelBuilder.Entity("eLab.DAL.Models.StaffProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StaffProfiles");
                });

            modelBuilder.Entity("eLab.DAL.Models.TestCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurnaroundHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("TestCatalogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Midicare_eLab.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Midicare_eLab.DAL.Models.Branch", b =>
                {
                    b.HasOne("Midicare_eLab.DAL.Models.User", "CreatedBy")
                        .WithMany("Branches")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("eLab.DAL.Models.AIChat", b =>
                {
                    b.HasOne("eLab.DAL.Models.PatientProfile", "PatientProfile")
                        .WithMany("AIChats")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eLab.DAL.Models.Result", "Result")
                        .WithMany("AIChats")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PatientProfile");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("eLab.DAL.Models.AIChatMessage", b =>
                {
                    b.HasOne("eLab.DAL.Models.AIChat", "AIChat")
                        .WithMany("AIChatMessages")
                        .HasForeignKey("AIChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Midicare_eLab.DAL.Models.User", "Sender")
                        .WithMany("AIChatMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AIChat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("eLab.DAL.Models.Booking", b =>
                {
                    b.HasOne("Midicare_eLab.DAL.Models.Branch", "Branch")
                        .WithMany("Bookings")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Midicare_eLab.DAL.Models.User", "CreatedBy")
                        .WithMany("Bookings")
                        .HasForeignKey("CreatedById");

                    b.HasOne("eLab.DAL.Models.PatientProfile", "PatientProfile")
                        .WithMany("Bookings")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLab.DAL.Models.StaffProfile", "StaffProfile")
                        .WithMany("Bookings")
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("CreatedBy");

                    b.Navigation("PatientProfile");

                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("eLab.DAL.Models.BookingItem", b =>
                {
                    b.HasOne("eLab.DAL.Models.Booking", "Booking")
                        .WithMany("BookingItems")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eLab.DAL.Models.Offer", "Offer")
                        .WithMany("BookingItems")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("eLab.DAL.Models.TestCatalog", "TestCatalog")
                        .WithMany("BookingItems")
                        .HasForeignKey("TestCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Offer");

                    b.Navigation("TestCatalog");
                });

            modelBuilder.Entity("eLab.DAL.Models.Notification", b =>
                {
                    b.HasOne("eLab.DAL.Models.Result", "Result")
                        .WithMany("Notifications")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Midicare_eLab.DAL.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eLab.DAL.Models.Offer", b =>
                {
                    b.HasOne("Midicare_eLab.DAL.Models.Branch", "Branch")
                        .WithMany("Offers")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Midicare_eLab.DAL.Models.User", "CreatedBy")
                        .WithMany("Offers")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eLab.DAL.Models.TestCatalog", "TestCatalog")
                        .WithMany("Offers")
                        .HasForeignKey("TestCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CreatedBy");

                    b.Navigation("TestCatalog");
                });

            modelBuilder.Entity("eLab.DAL.Models.PatientProfile", b =>
                {
                    b.HasOne("Midicare_eLab.DAL.Models.User", "CreatedBy")
                        .WithMany("CreatedPatientProfiles")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Midicare_eLab.DAL.Models.User", "User")
                        .WithOne("PatientProfile")
                        .HasForeignKey("eLab.DAL.Models.PatientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eLab.DAL.Models.PatientRecord", b =>
                {
                    b.HasOne("eLab.DAL.Models.Booking", "Booking")
                        .WithMany("PatientRecords")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Midicare_eLab.DAL.Models.Branch", "Branch")
                        .WithMany("PatientRecords")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLab.DAL.Models.PatientProfile", "PatientProfile")
                        .WithMany("PatientRecords")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLab.DAL.Models.Result", "Result")
                        .WithMany("PatientRecords")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Branch");

                    b.Navigation("PatientProfile");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("eLab.DAL.Models.Price", b =>
                {
                    b.HasOne("Midicare_eLab.DAL.Models.Branch", "Branch")
                        .WithMany("Prices")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Midicare_eLab.DAL.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLab.DAL.Models.TestCatalog", "TestCatalog")
                        .WithMany("Prices")
                        .HasForeignKey("TestCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Midicare_eLab.DAL.Models.User", null)
                        .WithMany("Prices")
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("CreatedBy");

                    b.Navigation("TestCatalog");
                });

            modelBuilder.Entity("eLab.DAL.Models.ReferenceRange", b =>
                {
                    b.HasOne("Midicare_eLab.DAL.Models.User", "CreatedBy")
                        .WithMany("ReferenceRanges")
                        .HasForeignKey("CreatedById");

                    b.HasOne("eLab.DAL.Models.ReportTemplate", "ReportTemplate")
                        .WithMany("ReferenceRanges")
                        .HasForeignKey("ReportTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ReportTemplate");
                });

            modelBuilder.Entity("eLab.DAL.Models.ReportTemplate", b =>
                {
                    b.HasOne("Midicare_eLab.DAL.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("eLab.DAL.Models.TestCatalog", "TestCatalog")
                        .WithMany("ReportTemplates")
                        .HasForeignKey("TestCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("TestCatalog");
                });

            modelBuilder.Entity("eLab.DAL.Models.Result", b =>
                {
                    b.HasOne("Midicare_eLab.DAL.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eLab.DAL.Models.BookingItem", "BookingItem")
                        .WithOne("Results")
                        .HasForeignKey("eLab.DAL.Models.Result", "BookingItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eLab.DAL.Models.PatientProfile", "PatientProfile")
                        .WithMany("Results")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eLab.DAL.Models.ReportTemplate", "ReportTemplate")
                        .WithMany("Results")
                        .HasForeignKey("ReportTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Midicare_eLab.DAL.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Midicare_eLab.DAL.Models.User", null)
                        .WithMany("ApprovedResults")
                        .HasForeignKey("UserId");

                    b.HasOne("Midicare_eLab.DAL.Models.User", null)
                        .WithMany("UploadedResults")
                        .HasForeignKey("UserId1");

                    b.Navigation("ApprovedBy");

                    b.Navigation("BookingItem");

                    b.Navigation("PatientProfile");

                    b.Navigation("ReportTemplate");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("eLab.DAL.Models.StaffChat", b =>
                {
                    b.HasOne("eLab.DAL.Models.Booking", "Booking")
                        .WithMany("StaffChats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLab.DAL.Models.PatientProfile", "PatientProfile")
                        .WithMany("StaffChats")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLab.DAL.Models.StaffProfile", "StaffProfile")
                        .WithMany("StaffChats")
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("PatientProfile");

                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("eLab.DAL.Models.StaffChatMessage", b =>
                {
                    b.HasOne("eLab.DAL.Models.StaffChat", "Chat")
                        .WithMany("StaffChatMessages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Midicare_eLab.DAL.Models.User", "Sender")
                        .WithMany("StaffChatMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("eLab.DAL.Models.StaffProfile", b =>
                {
                    b.HasOne("Midicare_eLab.DAL.Models.Branch", "Branch")
                        .WithMany("StaffProfiles")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Midicare_eLab.DAL.Models.User", "CreatedBy")
                        .WithMany("StaffProfiles")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Midicare_eLab.DAL.Models.User", "User")
                        .WithOne("StaffProfile")
                        .HasForeignKey("eLab.DAL.Models.StaffProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CreatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eLab.DAL.Models.TestCatalog", b =>
                {
                    b.HasOne("Midicare_eLab.DAL.Models.User", "CreatedBy")
                        .WithMany("TestCatalogs")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Midicare_eLab.DAL.Models.Branch", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Offers");

                    b.Navigation("PatientRecords");

                    b.Navigation("Prices");

                    b.Navigation("StaffProfiles");
                });

            modelBuilder.Entity("Midicare_eLab.DAL.Models.User", b =>
                {
                    b.Navigation("AIChatMessages");

                    b.Navigation("ApprovedResults");

                    b.Navigation("Bookings");

                    b.Navigation("Branches");

                    b.Navigation("CreatedPatientProfiles");

                    b.Navigation("Notifications");

                    b.Navigation("Offers");

                    b.Navigation("PatientProfile")
                        .IsRequired();

                    b.Navigation("Prices");

                    b.Navigation("ReferenceRanges");

                    b.Navigation("StaffChatMessages");

                    b.Navigation("StaffProfile")
                        .IsRequired();

                    b.Navigation("StaffProfiles");

                    b.Navigation("TestCatalogs");

                    b.Navigation("UploadedResults");
                });

            modelBuilder.Entity("eLab.DAL.Models.AIChat", b =>
                {
                    b.Navigation("AIChatMessages");
                });

            modelBuilder.Entity("eLab.DAL.Models.Booking", b =>
                {
                    b.Navigation("BookingItems");

                    b.Navigation("PatientRecords");

                    b.Navigation("StaffChats");
                });

            modelBuilder.Entity("eLab.DAL.Models.BookingItem", b =>
                {
                    b.Navigation("Results")
                        .IsRequired();
                });

            modelBuilder.Entity("eLab.DAL.Models.Offer", b =>
                {
                    b.Navigation("BookingItems");
                });

            modelBuilder.Entity("eLab.DAL.Models.PatientProfile", b =>
                {
                    b.Navigation("AIChats");

                    b.Navigation("Bookings");

                    b.Navigation("PatientRecords");

                    b.Navigation("Results");

                    b.Navigation("StaffChats");
                });

            modelBuilder.Entity("eLab.DAL.Models.ReportTemplate", b =>
                {
                    b.Navigation("ReferenceRanges");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("eLab.DAL.Models.Result", b =>
                {
                    b.Navigation("AIChats");

                    b.Navigation("Notifications");

                    b.Navigation("PatientRecords");
                });

            modelBuilder.Entity("eLab.DAL.Models.StaffChat", b =>
                {
                    b.Navigation("StaffChatMessages");
                });

            modelBuilder.Entity("eLab.DAL.Models.StaffProfile", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("StaffChats");
                });

            modelBuilder.Entity("eLab.DAL.Models.TestCatalog", b =>
                {
                    b.Navigation("BookingItems");

                    b.Navigation("Offers");

                    b.Navigation("Prices");

                    b.Navigation("ReportTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
